export const DEMO_DATA = {
  profile: {
    company_name: 'Studio Voorbeeld',
    btw_number: 'NL123456789B01',
    kvk_number: '12345678',
    iban: 'NL91ABNA0417164300',
    display_name: 'Jan Voorbeeld',
    address: 'Herengracht 100, 1015 BS Amsterdam',
  },
  invoices: [
    {
      number: 'FACT-2026-001',
      client: 'TechStart B.V.',
      amount: 3400,
      status: 'betaald' as const,
      date: '2026-03-15',
      description: 'Website redesign - fase 1',
    },
    {
      number: 'FACT-2026-002',
      client: 'Design Bureau Noord',
      amount: 1850,
      status: 'verzonden' as const,
      date: '2026-03-28',
      description: 'UX consultancy - maart',
    },
    {
      number: 'FACT-2026-003',
      client: 'Webwinkel Amsterdam',
      amount: 5200,
      status: 'concept' as const,
      date: '2026-04-01',
      description: 'E-commerce platform migratie',
    },
    {
      number: 'FACT-2026-004',
      client: 'Startup Hub NL',
      amount: 2100,
      status: 'betaald' as const,
      date: '2026-02-10',
      description: 'Landing page + branding',
    },
    {
      number: 'FACT-2026-005',
      client: 'TechStart B.V.',
      amount: 1600,
      status: 'verzonden' as const,
      date: '2026-04-05',
      description: 'Website redesign - fase 2',
    },
  ],
  clients: [
    {
      name: 'TechStart B.V.',
      email: 'info@techstart.nl',
      phone: '020-1234567',
      address: 'Keizersgracht 50, Amsterdam',
      kvk: '87654321',
    },
    {
      name: 'Design Bureau Noord',
      email: 'contact@designnoord.nl',
      phone: '050-9876543',
      address: 'Grote Markt 12, Groningen',
      kvk: '11223344',
    },
    {
      name: 'Webwinkel Amsterdam',
      email: 'hello@webwinkeldam.nl',
      phone: '020-5551234',
      address: 'Prinsengracht 200, Amsterdam',
      kvk: '55667788',
    },
    {
      name: 'Startup Hub NL',
      email: 'info@startuphub.nl',
      phone: '030-4445566',
      address: 'Jaarbeursplein 6, Utrecht',
      kvk: '99887766',
    },
  ],
  stats: {
    monthlyRevenue: 8450,
    openInvoices: 2,
    hoursThisWeek: 32,
    activeProjects: 3,
    btwThisQuarter: 1247.50,
  },
  timeEntries: [
    { date: '2026-04-14', project: 'Website Redesign', hours: 6.5, description: 'Homepage mockups uitwerken' },
    { date: '2026-04-14', project: 'E-commerce Migratie', hours: 2.0, description: 'Data mapping inventarisatie' },
    { date: '2026-04-13', project: 'Website Redesign', hours: 7.0, description: 'Responsive templates bouwen' },
    { date: '2026-04-13', project: 'UX Consultancy', hours: 1.5, description: 'Usability review meeting' },
    { date: '2026-04-12', project: 'E-commerce Migratie', hours: 8.0, description: 'API integratie Shopify' },
    { date: '2026-04-11', project: 'Website Redesign', hours: 4.0, description: 'Klantfeedback verwerken' },
    { date: '2026-04-11', project: 'UX Consultancy', hours: 3.0, description: 'Wireframes presentatie' },
  ],
  recentActivity: [
    'Factuur FACT-2026-001 betaald door TechStart B.V.',
    '4.5 uur geregistreerd voor Website Redesign',
    'Nieuwe klant toegevoegd: Webwinkel Amsterdam',
    'BTW rapport Q1 2026 gegenereerd',
    'Factuur FACT-2026-005 verzonden naar TechStart B.V.',
    'Offerte goedgekeurd door Design Bureau Noord',
  ],
};
